apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:D1g1talS0ul/kubernetes-apps.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path.basename}}' # Dynamically set project based on app directory name
      source:
        repoURL: git@github.com:D1g1talS0ul/kubernetes-apps.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
        passCredentials: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
