apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-unseal-key
  namespace: vault
  annotations:
    # See apps/grafana/templates/sealed-secrets-influxdb-token.yaml.
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  encryptedData:
    key: AgA8pzHq6z/kr3Mfq4ioS2iCXsLSXvXmRIhWJXoQc3MdUQ02SnRPTkkAn/KNkCeZuyUwCyjdxGNXYounncOlG7HEZkDTsFymeFO2IDjTuYOom4RGQjZ88vz0uNAWkGgS+01fqeFRigLQFuDXxXOop+QmX0G9N2ejb7iiADyMC0KtrRS4G8iLsS2opyM679SI/oueNo1c3bR3hFFc5fNJNO28BD2wAgte2i5z/ozQXG6O6my8WoWpZ28oIG8Ransw6//nwg4NGkVENf6OevetXxjYpSXdrEWn7SpsxueFzwASBrDXDrH4qbdotkwOps/qjB6H0BrzJFni/f+JnDEMFcPSx++GPIw1ONX4qL5NuqpuAS3NUn4xB/mF5fT3I4+yBBH0dbApTKadk5pBIiJOoqVR39Lhrnl3LBPVGFswx68UxpLXw65/pfTTPlOEdJin0W/AihKs/XVhXezQ/QaTwCw7RsqnbHsJwtTWiIGkc23wQY8mdh8nsjHMEXl52aKZI/jQzESCjg0VEtyn+JzSxrKGixSSAEe9/8uMU62GV4pidBQ207JaskfmZQM4ZkCNIlYbRVMHNnS1g0Li4rB5d3H2gxANh5nO/y1U/6UItm79pTi4fbd6/cRY34+NxnpmKKsnMBD/RVnLXHxjmf6mZZne7iCZjpQckViIh1iH1ubxsfU/Zi0gSDmzW+pRI3pUtsJr7rDRsSWHltLkz8giJ105Co6qSpGY48QxHYBYxAwjDLC3DJ4B0CcIfbvHfg==
  template:
    metadata:
      name: vault-unseal-key
      namespace: vault
