apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway-loki
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  listeners:
  - name: https-loki
    protocol: HTTPS
    port: 443
    hostname: "loki.cikli.com"
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      certificateRefs:
      - kind: Secret
        name: loki-1-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cilium-route-loki
  annotations:
    external-dns.alpha.kubernetes.io/hostname: loki.cikli.com
spec:
  parentRefs:
  - name: tls-gateway-loki
  hostnames:
  - "loki.cikli.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: loki-loki-distributed-distributor
      port: 3100
