apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/D1g1talS0ul/kubernetes-apps.git
      revision: HEAD
      directories:
  - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/D1g1talS0ul/kubernetes-apps.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles: '{{path}}/values.yaml'
        kustomize:
          components:
          - '{{path.basename}}/components/create-namespace'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        # - CreateNamespace=true