apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/D1g1talS0ul/kubernetes-apps.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/D1g1talS0ul/kubernetes-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          version: v3
          skipSchemaValidation: true
          skipTests: false
        #https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/helm.md
          valueFiles: 
          - '{{.path}}/values.yaml'
          ignoreMissingValueFiles: true
        kustomize:
          components:
          - '{{.path.basename}}/components/create-namespace'
          - '{{.path.basename}}/components/server-side-apply'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        # - CreateNamespace=true