# helm-values/loki-values.yaml

loki:
  auth_enabled: false  # Disable authentication for simplicity (NOT RECOMMENDED for production)

singleBinary:
  replicas: 1 # Start with a single replica for testing.  Scale up for production.

commonStorageConfig:
  type: filesystem
  filesystem:
    directory: /data/loki  # Directory on the persistent volume

storage:
  type: 'filesystem'  # Use the filesystem for storage (good for testing).
  filesystem:
    chunks_directory: /data/loki/chunks
    rules_directory: /data/loki/rules

persistence:
  enabled: true # Enable persistent storage
  size: 10Gi   # Request 10GB of storage
  # storageClassName: ""  # Optional: Specify a specific StorageClass. If empty, uses the default.

# Configure Promtail (log shipper - VERY IMPORTANT)
promtail:
  enabled: true
  config:
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push  # URL to push logs to Loki