apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana
  namespace: monitoring
spec:
  description: Grafana Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources that are removed from Git
      selfHeal: true # Automatically correct any deviations from the desired state in Git
    syncOptions:
      - CreateNamespace=true # Create the 'argocd' namespace if it doesn't exist
