apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Grafana
  namespace: argocd
spec:
  description: Grafana Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
