apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default # Change if you use a custom Argo CD project
  source:
    repoURL: 'git@github.com:D1g1talS0ul/kubernetes-apps.git' # Your Git repository URL
    targetRevision: HEAD # Or a specific branch/tag
    path: grafana/helm-charts/grafana # Path to your Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml # Specify your custom values.yaml if needed
  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes API server
    namespace: grafana # Target namespace for Grafana
  syncPolicy:
    automated: # Enable automated sync
      prune: true # Prune resources that are no longer in Git
      selfHeal: true # Automatically revert out-of-sync changes
    syncOptions:
      - CreateNamespace=true # Create the namespace if it doesn't exist