{
 "title": "UniFi-Poller: Client Insights - InfluxDB",
 "description": "Unpoller v2.9  Displays detailed information for clients in a UniFi network.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now-5s" },
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"source\" "
   },
   {
    "name": "Site",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"site_name\"  WHERE source =~ /^${Controller:regex}$/ "
   },
   {
    "name": "AP",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"ap_name\" WHERE site_name =~ /^${Site:regex}$/ "
   },
   {
    "name": "Switch",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"sw_name\" WHERE site_name =~ /^${Site:regex}$/ "
   },
   {
    "name": "Wireless",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"name\" WHERE site_name =~ /^${Site:regex}$/ AND ap_name =~ /^${AP:regex}$/ AND is_wired=false"
   },
   {
    "name": "Wired",
    "query": "SHOW TAG VALUES FROM \"clients\" WITH KEY = \"name\" WHERE site_name =~ /^${Site:regex}$/ AND sw_name =~ /^${Switch:regex}$/ AND is_wired=true"
   },
   {
    "name": "Identifier",
    "query": "$tag_name, $tag_name $tag_mac, $tag_mac"
   }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "channel_name" ], "type": "tag" },
      { "params": [ "radio_name" ], "type": "tag" },
      { "params": [ "radio_proto" ], "type": "tag" },
      { "params": [ "ap_name" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" },
      { "params": [ "oui" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT last(\"ip\") AS \"Address\", last(\"note\") AS \"Note\", last(\"network\") AS \"Network\" FROM \"clients\" WHERE (\"is_wired\" = 'false' AND \"ap_mac\" =~ /^${AP:regex}$/) AND $timeFilter GROUP BY \"mac\", \"oui\", \"channel_name\", \"radio\", \"name\", \"ap_mac\"",
     "select": [
      [
       { "params": [ "essid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ESSID" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sw_port" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "oui" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT last(\"ip\") AS \"Address\", last(\"note\") AS \"Note\", last(\"network\") AS \"Network\" FROM \"clients\" WHERE (\"is_wired\" != 'false' AND \"name\" =~ /^${Client:regex}$/ AND \"site_name\" =~ /^${Site:regex}$/) AND $timeFilter GROUP BY \"sw_port\", \"mac\", \"oui\", \"use_fixedip\", \"name\"",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^${Wired:regex}$/" },
      { "condition": "AND", "key": "sw_name", "operator": "=~", "value": "/^${Switch:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Wired",
     "groupBy": [
      { "params": [ "channel_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 5m AND (\"site_name\" =~ /^${Site:regex}$/ AND \"name\" =~ /^${Wired:regex}$/ AND sw_name =~ /^${Switch:regex}$/ ) GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Channel $tag_channel_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 5m AND (\"site_name\" =~ /^${Site:regex}$/ AND \"name\" =~ /^${Wireless:regex}$/ AND ap_name =~ /^${AP:regex}$/ ) GROUP BY \"channel_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_radio_proto",
     "groupBy": [
      { "params": [ "channel_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT count(distinct(\"hostname\")) FROM \"clients\" WHERE  $timeFilter  AND \"ap_name\" =~ /^${AP:regex}$/ AND \"site_name\" =~ /^${Site:regex}$/  AND \"name\" =~ /^${Wireless:regex}$/ GROUP BY radio_proto",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_oui",
     "groupBy": [
      { "params": [ "channel_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 5m AND site_name =~ /^${Site:regex}$/ AND ((\"name\" =~ /^${Wireless:regex}$/ AND \"ap_name\" =~ /^${AP:regex}$/) OR (\"name\" =~ /^${Wired:regex}$/ AND \"sw_name\" =~ /^${Switch:regex}$/ )) AND \"oui\" != '' GROUP BY \"oui\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "OS/Dev Class/ID Breakdown",
   "type": "piechart",
   "description": "No real idea what these numbers are, but Unifi provides them, so I made a cool pie chart out of them. What's your pie chart look like?",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_os_class, $tag_os_name, $tag_dev_cat, $tag_dev_family, $tag_dev_id,",
     "groupBy": [
      { "params": [ "channel_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 5m AND site_name =~ /^${Site:regex}$/ AND ((\"name\" =~ /^${Wireless:regex}$/ AND \"ap_name\" =~ /^${AP:regex}$/) OR (\"name\" =~ /^${Wired:regex}$/ AND \"sw_name\" =~ /^${Switch:regex}$/ )) GROUP BY \"os_class\", \"os_name\", \"dev_cat\", \"dev_family\", \"dev_id\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "graph",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Rx is on the negative axis. Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(sum(\"wired-rx_bytes\"), 1s) AS \"Rx\", derivative(sum(\"wired-tx_bytes\"), 1s) AS \"Tx\" FROM \"clients\" WHERE (\"name\" !~ /^amazon-|camera|cam$/ AND \"name\" =~ /^${Wired:regex}$/ AND \"site_name\" =~ /^${Site:regex}$/ AND \"sw_name\" =~ /^${Switch:regex}$/) AND $timeFilter GROUP BY time($__interval),\"name\",\"mac\"fill(none)",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "!~", "value": "/^amazon-|camera|cam$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^${Wired:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
      { "condition": "AND", "key": "sw_name", "operator": "=~", "value": "/^${Switch:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "graph",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "!~", "value": "/^amazon-|camera|cam$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Client / AP",
   "type": "state-timeline",
   "description": "Shows which wireless radio a client is connected to. Setting AP does not change this.",
   "gridPos": { "x": 0, "y": 63, "h": 16, "w": 12 },
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "select": [
      [
       { "params": [ "radio_desc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client / IP",
   "type": "state-timeline",
   "description": "Shows IPs assigned to non-static clients. Clients with many changes may indicate misconfiguration or two clients sharing the same name.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT \"ip\" FROM \"clients\" WHERE \"use_fixedip\" != 'true' AND \"name\" =~ /^${Client:regex}$/ AND (\"ap_name\" =~ /^${AP:regex}$/ OR \"sw_name\" =~ /^${Switch:regex}$/) AND \"site_name\" =~ /^${Site:regex}$/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    },
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT \"ip\" FROM \"clients\" WHERE \"use_fixedip\" != 'true' AND \"name\" =~ /^${Client:regex}$/ AND (\"ap_name\" =~ /^${AP:regex}$/ OR \"sw_name\" =~ /^${Switch:regex}$/) AND \"site_name\" =~ /^${Site:regex}$/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wired:regex}$/" },
      { "condition": "AND", "key": "sw_name", "operator": "=~", "value": "/^${Switch:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Echos & FireTVs",
   "type": "graph",
   "description": "Amazon Devices TX / RX bytes per second (calculated in 30 second buckets). Rx is on the native axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, don't fret, just don't include this graph in the new dashboards you're building. :)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "alias": "e [[Identifier]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^amazon-/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^${Wired:regex}$/" },
      { "condition": "AND", "key": "sw_name", "operator": "=~", "value": "/^${Switch:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    },
    {
     "alias": "w [[Identifier]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^amazon-/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Cameras",
   "type": "graph",
   "description": "Cameras TX / RX bytes per second. Rx is on the negative axis. Cameras probably don't do much Tx. If you don't have cameras, don't include this graph on your dashboards. This graph shows any device with the word \"camera\" in its name and has nothing to do with UniFi Protect.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT non_negative_derivative(sum(\"wired-rx_bytes\"), 1s) AS \"Rx\", non_negative_derivative(sum(\"wired-tx_bytes\"), 1s) AS \"Tx\" FROM \"clients\" WHERE \"name\" =~ /camera|cam$/ AND \"site_name\" =~ /^${Site:regex}$/ AND (\"sw_name\" =~ /^${Switch:regex}$/ OR \"ap_name\" =~ /^${AP:regex}$/) AND $timeFilter GROUP BY time($__interval), \"name\", \"mac\"",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/camera|cam$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
      { "condition": "AND", "key": "sw_name", "operator": "=~", "value": "/^${Switch:regex}$/" },
      { "condition": "OR", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "RSSI Quality" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short", "label": "Noise" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "noise" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "graph",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "tx_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "Attempts / Second" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "wifi_tx_attempts" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "graph",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rx_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short", "label": "Attempts / Second" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "tx_retries" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Transmit Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "tx_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Anomalies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Anomalies" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "anomalies" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Satisafaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "satisfaction" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Roam Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short", "label": "Anomalies" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "roam_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[Identifier]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${Wireless:regex}$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^${AP:regex}$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
     ]
    }
   ]
  }
 ]
}