{
 "title": "UniFi-Poller: Network Sites - InfluxDB",
 "description": "Unpoller v2.9  Displays detailed information for network Sites in a UniFi controller.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now-5s" },
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "show tag values from \"subsystems\" with key=\"source\""
   },
   {
    "name": "Site",
    "query": "show tag values from \"subsystems\" with key=\"site_name\" WHERE source =~ /^${Controller:regex}$/ "
   },
   {
    "name": "Subsystem",
    "query": "show tag values from \"subsystems\" with key=\"subsystem\""
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "Each site contains 5 subsystems: wan, lan, wlan, www, vpn. Each subsystem contains data specific to that system, but every subsystem shares the same fields. \nThis means that most fields you find appear empty. That means the field is probably for a different subsystem.\nThe site metrics tend to contain a lot of data about the local USG.\nNote: The three singlestat panels with thresholds do not have a subsystem selected and they may not be entirely accurate.\n\n"
  },
  {
   "title": "Site: $Site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Site",
   "collapsed": true,
   "panels": [
    {
     "title": "WWW Latency",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "www" }
       ]
      }
     ]
    },
    {
     "title": "Speed Test Ping",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "speedtest_ping" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "www" }
       ]
      }
     ]
    },
    {
     "title": "Gateway CPU",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "gw_cpu" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
       ]
      }
     ]
    },
    {
     "title": "Gateway Memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "gw_mem" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
       ]
      }
     ]
    },
    {
     "title": "WWW Subsystem",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "desc" ], "type": "tag" }
       ],
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "rx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RxRate" ], "type": "alias" }
        ],
        [
         { "params": [ "tx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TxRate" ], "type": "alias" }
        ],
        [
         { "params": [ "xput_down" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "xPutRx" ], "type": "alias" }
        ],
        [
         { "params": [ "xput_up" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "xPutTx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "www" }
       ]
      }
     ]
    },
    {
     "title": "Gateways",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_gw" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
       ]
      }
     ]
    },
    {
     "title": "Switches",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_sw" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "lan" }
       ]
      }
     ]
    },
    {
     "title": "WAPs",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_ap" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
       ]
      }
     ]
    },
    {
     "title": "VPN Users",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_user" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "vpn" }
       ]
      }
     ]
    },
    {
     "title": "WLAN Users",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_user" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
       ]
      }
     ]
    },
    {
     "title": "LAN Users",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_user" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "lan" }
       ]
      }
     ]
    },
    {
     "title": "Total Users",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_sta" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
       ]
      }
     ]
    },
    {
     "title": "VPN Subsystem",
     "type": "table",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "status" ], "type": "tag" }
       ],
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "remote_user_num_inactive" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Inactive" ], "type": "alias" }
        ],
        [
         { "params": [ "remote_user_num_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Active" ], "type": "alias" }
        ],
        [
         { "params": [ "remote_user_rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RX" ], "type": "alias" }
        ],
        [
         { "params": [ "remote_user_tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "vpn" }
       ]
      }
     ]
    },
    {
     "title": "LAN Subsystem",
     "type": "table",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "lan_ip" ], "type": "tag" }
       ],
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_user" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Users" ], "type": "alias" }
        ],
        [
         { "params": [ "num_iot" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IoT" ], "type": "alias" }
        ],
        [
         { "params": [ "num_guest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Guests" ], "type": "alias" }
        ],
        [
         { "params": [ "num_sw" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Switches" ], "type": "alias" }
        ],
        [
         { "params": [ "num_adopted" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Adopted" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "lan" }
       ]
      }
     ]
    },
    {
     "title": "WWW Drops",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "drops" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "www" }
       ]
      }
     ]
    },
    {
     "title": "Adopted",
     "type": "singlestat",
     "description": "This panel currently does not select a subsystem, so the data reflected here may only be fore 1 random system. Keep this in mind when you build your own graphs from this data.",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_adopted" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "Disabled",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_disabled" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "Disconnected",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_disconnected" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "Alarms",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_new_alarms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "WLAN IoT",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_iot" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
       ]
      }
     ]
    },
    {
     "title": "Guests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_guest" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
       ]
      }
     ]
    },
    {
     "title": "WAN Subsystem",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "gw_name" ], "type": "tag" },
        { "params": [ "wan_ip" ], "type": "tag" }
       ],
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "rx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Rx Rate" ], "type": "alias" }
        ],
        [
         { "params": [ "tx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Tx Rate" ], "type": "alias" }
        ],
        [
         { "params": [ "num_new_alarms" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Alarms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" },
        { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
       ]
      }
     ]
    },
    {
     "title": "Site $Site Data Transfer",
     "type": "graph",
     "description": "Shows data transfer for each subsystem on the site. RX is on the negative axis.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "alias": "$tag_subsystem $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsystem" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "subsystems",
       "query": "SELECT max(\"rx_bytes-r\") AS \"Bytes RX\", max(\"tx_bytes-r\") AS \"Bytes TX\" FROM \"subsystems\" WHERE (\"site_name\" =~ /^${Site:regex}$/) AND $timeFilter GROUP BY time($__interval), \"subsystem\" fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Bytes RX" ], "type": "alias" }
        ],
        [
         { "params": [ "tx_bytes-r" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Bytes TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "Site $Site Client Counts",
     "type": "graph",
     "description": "This graphs shows clients connected to the site.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsystem $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsystem" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "subsystems",
       "select": [
        [
         { "params": [ "num_user" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Users" ], "type": "alias" }
        ],
        [
         { "params": [ "remote_user_num_active" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Remote Active" ], "type": "alias" }
        ],
        [
         { "params": [ "remote_user_num_inactive" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Remote Inactive" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    },
    {
     "title": "Data Transfer by Category",
     "type": "graph",
     "description": "This graph only works if DPI is enabled on the controller and DPI collection is enabled in Unpoller. Rx is on the negative axis.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_category $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" }
       ],
       "measurement": "sitedpi",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Bytes Rx" ], "type": "alias" }
        ],
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Bytes Tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "site_name", "operator": "=~", "value": "/^${Site:regex}$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}