k8s-monitoring:
  cluster:
    name: "mine"

  externalServices:
    prometheus:
        host: http://prometheus-k8s.monitoring.svc:9090
        authMode: none
        writeEndpoint: '/api/v1/push'
    loki:
        host: http://loki-loki-distributed-gateway.loki.svc
        authMode: none
        processors:
          batch:
            size: 16384
            maxSize: 0
            timeout: 20s
          memory_limiter:
            check_interval: 1s
            limit_memory: 256MB
            spike_limit_memory: 128MB
 
  metrics:
    enabled: true
    autoDiscover:
      enabled: true
    cost:
      enabled: false
    node-exporter:
      enabled: true
    cadvisor:
      enabled: true
      metricsTuning:
        dropEmptyImageLabels: false
        dropEmptyContainerLabels: false
        keepPhysicalNetworkDevices: [".*"]
      extraRelabelingRules: |-
        rule {
          source_labels = ["__meta_kubernetes_node_label_name"]
          regex = "(.*)"
          target_label = "node_pool"
        }
        rule {
          source_labels = ["__meta_kubernetes_node_label_topology_kubernetes_io_zone"]
          regex = "(.*)"
          target_label = "node_zone"
        }
        rule {
          source_labels = ["__meta_kubernetes_node_label_hostname"]
          regex = "(.*)"
          target_label = "node_hostname"
        }
    kubelet:
      enabled: true
      extraRelabelingRules: |-
        rule {
          source_labels = ["__meta_kubernetes_node_label_name"]
          regex = "(.*)"
          target_label = "node_pool"
        }
        rule {
          source_labels = ["__meta_kubernetes_node_label_topology_kubernetes_io_zone"]
          regex = "(.*)"
          target_label = "node_zone"
        }
        rule {
          source_labels = ["__meta_kubernetes_node_label_hostname"]
          regex = "(.*)"
          target_label = "node_hostname"
        }
 
  logs:
    enabled: true
    pod_logs:
      enabled: true
    cluster_events:
      enabled: true
  
  traces:
    enabled: false
  receivers:
    grpc:
      enabled: true
    http:
      enabled: true
    jaeger:
      grpc:
        enabled: true
      thriftBinary:
        enabled: true
      thriftCompact:
        enabled: true
      thriftHttp:
        enabled: true
    zipkin:
      enabled: false
    grafanaCloudMetrics:
      enabled: false
  processors:
    batch:
      # Amount of data to buffer before flushing the batch.
      size: 16384
      # Upper limit of a batch size. When set to 0, there is no upper limit.
      maxSize: 0
      # How long to wait before flushing the batch.
      timeout: 20s
      queue_size: 4096 
      max_memory: "256MB"
  opencost:
    enabled: false
    config:
      name: null
      create: true
  profiles:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-operator-crds:
    enabled: true
  grafana-agent: {}
  grafana-agent-logs: {}
  alloy-events:
    logging:
      level: error
  alloy-logs:
    logging:
      level: error
  alloy:
    logging:
      level: error
    alloy:
      resources:
        requests:
          cpu: "100m"
          memory: "2Gi"
    controller:
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 70