k8s-monitoring:
  cluster:
    name: "mine"

  clusterMetrics:
    enabled: true
    destinations:
      - http://prometheus-k8s.monitoring.svc:9090

  clusterEvents:
    enabled: true
    destinations:
      - http://loki-loki-distributed-gateway.loki.svc
  
  nodeLogs:
    enabled: true
    destinations:
      - http://loki-loki-distributed-gateway.loki.svc

  podLogs:
    enabled: true
    destinations:
      - http://loki-loki-distributed-gateway.loki.svc