cluster:
  name: mine

destinations:
  - name: localLoki
    type: loki
    url: http://loki-loki-distributed-gateway.loki.svc:3100

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogs:
  enabled: true
