# yamllint disable rule:line-length rule:comments-indentation
cluster:
  name: mine

destinations:
  - name: localLoki
    type: loki
    url: http://loki-loki-distributed-gateway.loki.svc:3100

  - name: localPrometheus
    type: prometheus
    url: http://prometheus-k8s.monitoring.svc:9090

clusterMetrics:
  enabled: true
  destinations: localPrometheus

clusterEvents:
  enabled: true
  destinations: localLoki

nodeLogs:
  enabled: true
  destinations: localLoki

podLogs:
  enabled: true
  destinations: localLoki

prometheusOperatorObjects:
  enabled: true
  destinations: localPrometheus

selfReporting:
  enabled: false