cluster:
  name: my-cluster

destinations:
  - name: localLoki
    type: loki
    url: http://loki-loki-distributed-gateway.loki.svc:3100

  - name: localPrometheus
    type: prometheus
    url: http://prometheus-k8s.monitoring.svc:9090

clusterMetrics:
  enabled: true
  destinations:
    - name: localPrometheus

clusterEvents:
  enabled: true
  destinations:
    - name: localLoki

nodeLogs:
  enabled: true
  destinations:
    - name: localLoki

podLogs:
  enabled: true
  destinations:
    - name: localLoki

prometheusOperatorObjects:
  enabled: true
  destinations:
    - name: localPrometheus

selfReporting:
  enabled: false