k8s-monitoring:
  cluster:
    name: "mine"

  destinations:
    - name: prometheus
      type: prometheus
      url: http://prometheus-k8s.monitoring.svc:9090
    - name: loki
      type: loki
      url: http://loki-loki-distributed-gateway.loki.svc

  clusterMetrics:
    enabled: true

  clusterEvents:
    enabled: true

  nodeLogs:
    enabled: true

  podLogs:
    enabled: true
