k8s-monitoring:
  cluster:
    name: "mine"

  destinations:
    - name: prometheus
      type: prometheus
      url: http://prometheus-k8s.monitoring.svc:9090
    - name: loki
      type: loki
      url: http://loki-loki-distributed-gateway.loki.svc

  clusterEvents:
    enabled: true

  clusterMetrics:
    enabled: true
    apiServer:
      enabled: true
      jobLabel: apiserver
    kubelet:
      jobLabel: kubelet
      extraMetricProcessingRules: |
        rule {
          replacement   = "/metrics"
          target_label  = "metrics_path"
        }
    cadvisor:
      jobLabel: kubelet
      extraMetricProcessingRules: |
        rule {
          replacement   = "/metrics/cadvisor"
          target_label  = "metrics_path"
        }
    node-exporter:
      jobLabel: node-exporter
      metricsTuning:
        includeMetrics:
          - node_uname_info
          - node_time_seconds
          - node_disk_io_time_seconds_total
          - node_disk_io_time_weighted_seconds_total
          - node_load1
          - node_vmstat_pgmajfault
    kube-state-metrics:
      jobLabel: kube-state-metrics
    windows-exporter:
      deploy: false
      enabled: false

  prometheusOperatorObjects:
    enabled: true
    crds:
      deploy: true

  podLogs:
    enabled: true

  alloy-metrics:
    enabled: true

  alloy-logs:
    enabled: true

  alloy-singleton:
    enabled: true

  integrations:
    collector: alloy-singleton