pihole:
  hostname: "ns1"

  serviceDns:
    loadBalancerIP: 192.168.1.96
    annotations:
      "lbipam.cilium.io/ips": "192.168.1.96"
      "lbipam.cilium.io/sharing-key": "dns"
    type: LoadBalancer
    mixedService: true

  persistentVolumeClaim:
    enabled: true

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 127.0.0.1
    - 192.168.1.5
  serviceDhcp:
    enabled: false
    
  #! use an existing secret in a prod env
  adminPassword: "admin"

  dnsmasq:
    customDnsEntries:
      - address=/nas/192.168.178.10
  
    customCnameEntries:
      - cname=foo.nas,nas

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }