pihole:
  hostname: "ns1"
  privileged: true
  hostNetwork: true

  dnsHostPort:
    enabled: true
    port: 53

  serviceDns:
    annotations:
      lbipam.cilium.io/ips: 192.168.1.96
      lbipam.cilium.io/sharing-key: dns
    type: LoadBalancer
    mixedService: true

  persistentVolumeClaim:
    enabled: true

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 127.0.0.1
      - 192.168.1.5
  serviceDhcp:
    enabled: false
    
  #! use an existing secret in a prod env
  adminPassword: "admin"

  dnsmasq:
    customDnsEntries:
      - address=/foo.bar/192.168.178.10
      - address=/bar.foo/192.168.178.11
    customCnameEntries:
      - cname=cname.foo.bar,foo.bar
      - cname=cname.bar.foo,bar.foo

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }