apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |-
    - op: add
      path: /spec/syncPolicy/syncOptions/-
      value: ServerSideApply=true