apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    annotationSelector: "argocd.argoproj.io/tracking-id=k8s-monitoring"
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: '/metadata/annotations/argocd.argoproj.io~1sync-options'
      value: ServerSideApply=true