apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    name: .*
    version: v1
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: '/metadata/annotations/argocd.argoproj.io~1sync-options'
      value: ServerSideApply=true