apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:D1g1talS0ul/kubernetes-apps.git
        revision: main
        directories:
          - path: projects/*
  template:
    metadata:
      name: '{{path.basename}}-project'
    spec:
      project: default # This should be a pre-existing project in Argo CD
      source:
        repoURL: git@github.com:D1g1talS0ul/kubernetes-apps.git
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster  # Use 'name: in-cluster' for managing resources in the same cluster
        namespace: argocd # Namespace where the AppProject resources will be created
      syncPolicy:
        automated:
          prune: true  # Automatically delete resources that are removed from Git
          selfHeal: true # Automatically correct any deviations from the desired state in Git
        syncOptions:
          - CreateNamespace=true # Create the 'argocd' namespace if it doesn't exist
