---
grafana:
  # -- Deploy Grafana if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration) for full values reference.
  enabled: true
  # -- Grafana data sources config. Connects to all three by default
  datasources:
    datasources.yaml:
      apiVersion: 1
      # -- Datasources linked to the Grafana instance. Override if you disable any components.
      datasources:
        # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
        - name: Prometheus
          uid: prom
          type: prometheus
          isDefault: true
          access: proxy
          editable: false
          url: http://prometheus-k8s.monitoring.svc:9090
          version: 1
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

  dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        revision: 37
        datasource: Prometheus
    argoCD:
      gnetId: 14584
      revision: 1  
      datasource: Prometheus
    coreDNS:
      gnetId: 14981
      revision: 2
      datasource: Prometheus

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

loki:
  # -- Deploy Loki if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#values) for full values reference.
  enabled: false

