---
grafana:
  # -- Deploy Grafana if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration) for full values reference.
  enabled: true
  # -- Grafana data sources config. Connects to all three by default
  datasources:
    datasources.yaml:
      apiVersion: 1
      # -- Datasources linked to the Grafana instance. Override if you disable any components.
      datasources:
        # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
        - name: Prometheus
          uid: prom
          type: prometheus
          url: http://prometheus-k8s.monitoring.svc.cluster.local
          isDefault: true
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password

loki:
  # -- Deploy Loki if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#values) for full values reference.
  enabled: false

