apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TAKEN FROM
# https://github.com/argoproj/argoproj-deployments/tree/master
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml

# extensions controller component
# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests


# https://docs.cilium.io/en/stable/configuration/argocd-issues/#argo-cd-deletes-customresourcedefinitions
patches:
- path: overlays/production/argocd-cmd-params-cm.yaml
- path: overlays/mine/cilium.yaml
