apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# TAKEN FROM
# https://github.com/argoproj/argoproj-deployments/tree/master
# resources:
# - base/argo-cd-issuer.yaml
# - base/argo-cd-certificate.yaml
# - base/argo-cd-ui-ingress.yaml
# - base/rollouts-extension.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

patches:
- path: overlays/mine/cilium.yaml
# - path: overlays/production/argo-cd-cm.yaml
# - path: overlays/production/argocd-server-service.yaml
# - path: overlays/production/argocd-notifications-controller-deploy.yaml
# - path: overlays/production/argocd-notifications-cm.yaml
# - path: overlays/production/argocd-cmd-params-cm.yaml
# - path: overlays/production/argocd-rbac-cm.yaml
# - path: https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml

