apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway-grafana
  namespace: '{{path.basename}}'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  listeners:
  - name: https-grafana
    protocol: HTTPS
    port: 443
    hostname: "grafana.cikli.com"
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      certificateRefs:
      - kind: Secret
        name: grafana-1-tls
        namespace: '{{path.basename}}'
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cilium-route-grafana
  namespace: '{{path.basename}}'
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.cikli.com
spec:
  parentRefs:
  - name: tls-gateway-grafana
  hostnames:
  - "grafana.cikli.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grafana
      namespace: '{{path.basename}}'
      port: 80
