---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-unpoller-token
  namespace: grafana
spec:
  encryptedData:
    INFLUXDB_UNPOLLER_TOKEN: AgA22HWQg1i7RI+AVY7HWnUCOHX5i43U+hwyPktEVqJG3SkrdSYs0BdhNocMlR1KKfqDFANIyVA899I0WWAPU1b1/e5uOcjQTw/ecUpaYJi1XrCQGQjN2qCW3mnBdBG1w54lQNGe8mXpHIsK+RcKhLtErx09CbGXf37FerSYSZEtIat7L24XYW0kJLJ+6A03su+PpiSg/5eR12ExsgafEi5++HPnlxjtN6jONl3DaVwtzRafn48/Mp8ZMlfS/qr5OCmZhZO17xbXpcQCt1kyv2KEsBVoUDGUkC4bEoU+qtF6/N4kxCcNcCQHjYyqecBfmnjwbMfwjGQUtpRHa1Hz8yfHKOTX6+RhAMfOUIZIKe5ZZBXZpGOTrkWhEah5YAynn0CejoRfPWwqssHIRi+zeYyx9AP3LSZ8asMzIjgt6c8HuCqvEGqwtydLP1UGxKN4c935TwWxHzeerszomD1Zn5GaWsnp5w7tdHT+MWwdAeIzvc2dYOD1J+HcoYQ2VXyYto0BHZG3ErdLdr8pl5weHfypfG6FeGI2kBqR1RslJlKzlVhRwsyUrdRhPF15WyPUX9fccGDG7wlLJoAZYoLW3TH5pGmRJkFauHWOVtGXHtqUWGe+FBx5KtkCr+eq78Umh0YbzuSPFZ4IOPeW3G0IpJ8DFc77NTSJxPyLZcUSA3ekKvrb0ultg25GgFRHd81EVEcqlFI6GRMxnnJ/ga4DFEUQceNIFL7RGw5MKaUeIGJdscZNDA+jz159AK0DRGP25xl3jc9xHfvQ13J1s/mFpzpZAeETZE5Txl1fQ/U7SnLEP2Sry8uaR+OOhpeFrQ==
  template:
    metadata:
      name: influxdb-unpoller-token
      namespace: grafana
