---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCvj3fESg2xoDKqIZJ4XGCvvdf6j9XcjE5kQvOXVfRXQj/DB8E/rHLg7ZfMl7ex3zuT9aX1KigoHn+NHs8wcLEgIHwRJI9IcozA37N9Y6xEMxSJia9/0AetvRieVcspj/5aRRModSlRpVcIf+fHE4nWWj6+K36YhGiRxksAnszT7ClfV23ktyilOa/hBlMrAFmdEMgGB+m4Gf49w7jXKhdtV5xIQq5Z1yoBYfPFvKL31XGTaJZG6BJ9qsXpSLcozdQG2MZjkhtlX2KmLeg69mS+lUmzH7zgfCPizBgqn5E/snP99qRH1b5zWTe3vvCLPv7mWk1LnaZIOIjvq6UfMrsG+WJfxodgtFOE/lglbpB376PtAY6JRVFxShAEApVw7FnaGuRFOXIK2xI1FRbF1C2q0Dc8e88XCe/sRpQ/HkupxwXffx0+GUnsbzUvMs85dPN94G8ZUY1+uXwEdo3fLAboK55S0z5wbs8ioW5Z6vgcBpWelzkdF/VyAkwiwetdImTViRFv1jic71CZwPkU2N1pEvdN97COy8VNz0Iz+wIeZyCM450ArUojZphyaVQU3PZ64Jvv0UZyBg522i4H4fezXOC38fFYBHXaY5Zp/FTplO64hAGrVaDFn+kNeAH0KkGC4ffxHUegiGFvQLdQBSkMV/w4yNndzLAAylJ4duGE3uwE5S9OfUU6R5LFHEFbx/jY+NjT4f6JEw==
    admin-user: AgCK+GFkXmBkT+kb5H+G8qfm+sXGHaMlIVdT49JQMzVIx9PCK/RXK1kYwyLehnbx1dJAlxVYn6Lx+kUsoWE2gKrtIRQCrNs5mC/isSy0TIjjVNrBslD3/mErAaKyxcm9QZhfVq+A2Xm0bBlm5+DTG0NZpbVfKHWhVCwWGQBAmJpYmiFHcuV5G24mv0loXHMtua+AOYkQoI2hkFnoBqsyNut9ip60Ipoh/GCoM4XQVGXLmwRhZ7lWCq0ErgT90EhfXygObzllZZhmvkKfOKXYcaZvcrmMjnYQkpN0tGjGOYknfDdkuijnL0sCvTLb6pTtUBT4h2VYaZMY2AsXAqxNiFVhA+HHZoAd1IJNZK7pk59fe9rVz8ufHtlJgvbLkGq7bnpomYYKICg08d6LngLjSkE6ndmZTkXdvSvsSDFyFRmkaLuzn7sOPzKBjEJvsWUKwB1JXKDwh0Z/AU2vImIrdm/cF35x13vpVpZozToFmwksXRAahvF7Qtr+9lQKqRjugX3FxM8mtb9FsPG2g6znkP2CnHxVgkRikMJhbs+AOjGm6AafUebYByTxQO7/DN69ek/LMdFjtY1MbMy0FbGHO8sPfM6FRT3SVzAb98i2WWI5HaVdOTE5fzdDeUOPGqBj2kEFt8BkRjM+6yYZcqNHooH+ymZoxa1dbbkBPSHBAzxjX3f+FJK/tnmSM2zxa7RMm1T6r9ReLlpKLA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: grafana
