---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCoPztVCsoY/5JYaYVGa5+YVyRbfsR1LM7vSMHBFzWnGkVqJb7aAhyEU6X0D4smVTu0HU1KzAYdQOO65/4ttAfTh6QIq3pLq0rj/CrJmybVsXWSI4Ybw+dyHFexB5eyC2uUttH4MPq98Dwi1eckCdlZPJ1Nb4WArQm0H38xCU1qnJ6+JwVXcDIfV8bcOTDvQ7qn7wpoLVstTohaCFnk4WJ/xjEoQjrl4ftEazprQgsyAxcN82O+HQDkQLK5aS5OwwR4mKSkKC1OooFscs+AM+FnmdrFgljTtoESrKm8dpAsQeFmnTyD+zoghEk0suyaN1QXGdTvqwX8sKbwNpFwmVe6iGvpXbkmFV9GI3foxcfC8Al1Tz7KHFysTnn+kP9IpHe3zqN5U+YkP0jP4S+cBert9kocWTwyVSdkHiZWdxc9GOCG2nNwalupL0zHQWddqVk9W/hD8cyekEG31eC/KMpV8aZXdS0yXAGjJ1aNYFscjMv8r/pSdhC6GL6sq+ss65vEA6HAT/rdjnB90OY/FbL36R56O85X77oYOGmW/Zchn0mVEPtFL1qtLx/+7JN39YkiLP03NaQqJw0mSJFF9v8RIBiebzc+HVbzoR0S9NA7CVZowtB0qFFgIW3u5aA4fYcG43rjWDH0+1kH6EwdSLteJKb/RX7kgZR1wrhZR3XcUmhzhkRr6chYQUS0ZcWef1F/XGsS/jVYYw==
    admin-user: AgBMCKiZoJinrJ98veyIjLGdBK6gb4+3e7DXkb+elzsnVqspS9wvvSTK4ckjcq0cMOu96pAedeV+68dcA0zruh1h5wqvbX3maBDxDyoABkScs8XILp2G+5xe3tAQWNvfM1ZQoakLrntIpLFpQXK2wJvrEKZUcdkMyKpvj/8GNxFcP0QJ8kX/9xx+cD/7rp82TGNmiKWDsd4ZRnDAzV62hv4JQESLDGzr9VA2cXA7sT/xwK0DUvKIN98pIM6Zm+MkpT0g3Vkey0il9PVyhi/852o2AHL5kmZ0QaeqHm0n5h4uoYnBD3UOy0F3APEB3qNwg2PbFMzpqO7MumT6Wb+wCsPISB6nKNROCBicJu6dA0S8GcRxXli0XXHw+8oGO3BNIFzjrrQFGsjbynjyTMjy3WTKedT9Mm8kkt3t+ZGuAfFjREIUXTXxy2fYcYdtcoUE4AY6Wa4bRMhAYlmAAmYt8n3fiauZluXhWQCHvUH/9N2EW2uBdxu6sdQQgOGdCydzTDIWOMtoJTYc2OBhQKM/O2IBFYs4doD/B8FjfXquuuuAY4kpqJsZXvp15b+mi4Z6eQP4WRf9MsxZSOwN4Qxjb2WZuyzbLRBnQSL/woAARIEs0G3Nw73Ev4FW5DDPr9lwxFdzcoFFzPz5T5CGIhVUMKxgpsO3tk4t3obBjBC1WBMewP+i0lWxM6JcRyocTBEBD9OaEAk+fA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: grafana
